ExternalProject_Add(llvm-host-compiler-rt-builtin
    DOWNLOAD_COMMAND ""
    UPDATE_COMMAND ""
    SOURCE_DIR ${LLVM_SRC}
    CONFIGURE_COMMAND ${EXEC_HOST} ${CMAKE_COMMAND} -H<SOURCE_DIR>/compiler-rt/lib/builtins -B<BINARY_DIR>
        -GNinja
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/lib/clang/${clang_version}
        -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
        -DCMAKE_ASM_COMPILER=${CMAKE_C_COMPILER}
        -DCMAKE_C_COMPILER_WORKS=ON
        -DCMAKE_CXX_COMPILER_WORKS=ON
        -DCMAKE_ASM_COMPILER_WORKS=ON
        -DCMAKE_C_COMPILER_TARGET=${HOST_ARCH}
        -DCMAKE_DISABLE_FIND_PACKAGE_LLVM=ON
        -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON
        -DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON
        -DCOMPILER_RT_EXCLUDE_ATOMIC_BUILTIN=OFF
        -DCOMPILER_RT_CRT_USE_EH_FRAME_REGISTRY=OFF
        -DCOMPILER_RT_HAS_ATOMIC_KEYWORD=ON
        -DCOMPILER_RT_INCLUDE_TESTS=OFF
        -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON
        -DCOMPILER_RT_HAS_FNO_LTO_FLAG=OFF
        -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY
        "-DCMAKE_C_FLAGS='${tc_cflags} ${tc_compiler_rt} -flto=thin'"
        "-DCMAKE_CXX_FLAGS='${tc_cflags} ${tc_compiler_rt} -flto=thin'"
        "-DCMAKE_ASM_FLAGS='${tc_cflags} ${tc_compiler_rt}'"
    BUILD_COMMAND ${EXEC_HOST} "CCC_OVERRIDE_OPTIONS='x-fno-builtin +-fbuiltin'" ninja -C <BINARY_DIR>
    INSTALL_COMMAND ${EXEC_HOST} ${CMAKE_COMMAND} --install <BINARY_DIR>
    LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_INSTALL 1
)

cleanup(llvm-host-compiler-rt-builtin install)
