ExternalProject_Add(vvenc
    GIT_REPOSITORY https://github.com/fraunhoferhhi/vvenc.git
    SOURCE_DIR ${SOURCE_LOCATION}
    GIT_CLONE_FLAGS "--depth=1 --filter=tree:0"
    GIT_PROGRESS TRUE
    UPDATE_COMMAND ""
    CONFIGURE_ENVIRONMENT_MODIFICATION
        _IS_CONFIGURE=set:1
    CONFIGURE_COMMAND ${EXEC} ${CMAKE_COMMAND} -H<SOURCE_DIR> -B<BINARY_DIR>
        ${cmake_conf_args}
        -DVVENC_LIBRARY_ONLY=ON
        -DVVENC_ENABLE_BUILD_TYPE_POSTFIX=OFF
        -DVVENC_ENABLE_LINK_TIME_OPT=OFF
        -DVVENC_ENABLE_THIRDPARTY_JSON=OFF
        -DVVENC_ENABLE_WERROR=OFF
        -DCCACHE_FOUND=OFF
    BUILD_ENVIRONMENT_MODIFICATION
        _PACKAGE_NAME=set:${package}
        _BINARY_DIR=set:<BINARY_DIR>
        _IS_EXCEPTIONS_ALLOWED=set:1
    BUILD_COMMAND ${EXEC} ninja -C <BINARY_DIR>
    INSTALL_COMMAND ${EXEC} ${CMAKE_COMMAND} --install <BINARY_DIR>
    LOG_DOWNLOAD 1 LOG_UPDATE 1 LOG_CONFIGURE 1 LOG_BUILD 1 LOG_INSTALL 1
)

force_rebuild_git(vvenc)
cleanup(vvenc install)
